Fix CI: Remove non-existent qt6-svg-dev package
Ubuntu 22.04 doesn't have qt6-svg-dev package.
The correct package is libqt6svg6-dev which was already in the list.

Error: E: Unable to locate package qt6-svg-dev