Fix CI: Patch OpenTraceCapture Doxyfile path bug
OpenTraceCapture's Doxyfile has incorrect path that results in:
  build/build/doxygen/xml (duplicate 'build/')

This causes:
  error: Could not create output directory /tmp/opentracecapture/build/build/doxygen/xml
  fatal error: enums.hpp: No such file or directory

Root cause: Doxyfile uses $(BUILDDIR)/build/doxygen but BUILDDIR
already points to the build directory.

Fix: Patch Doxyfile to use $(BUILDDIR)/doxygen instead.

This is a workaround - should be fixed in OpenTraceCapture upstream.